# Generated by Django 3.1.4 on 2021-02-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user',
            new_name='wah',
        ),
    ]
